### ISSUE TITLE
When my gesture is stationary, the landmarks of the  output are still changing. how to solve this problem?

### ISSUE THREAD

**Issue by Mgz-97** [wolterlw/hand_tracking#36]
Hello, I modified the program to input a picture, but when a similar picture is input, the coordinates of the key points of the output gesture will be different. How to eliminate this difference? Thank you！

**Comment by wolterlw** [comment]
I don’t think this is possible because the neural net uses the whole image as an input, so even if you change a couple of pixels the result may be different. It shouldn’t vary too much, but it won’t be the exact same.
If you want to compare outputs you can define a template and then compute distance between it and further outputs.
